/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BasketItem { 'productId' : string, 'quantity' : bigint }
export interface Category {
  'name' : string,
  'subcategories' : Array<string>,
  'parent' : [] | [string],
}
export interface CategoryV2 {
  'name' : string,
  'subcategories' : Array<string>,
  'parent' : [] | [string],
}
export type Currency = { 'aud' : null } |
  { 'cad' : null } |
  { 'eur' : null } |
  { 'gbp' : null } |
  { 'usd' : null };
export type ExternalBlob = Uint8Array;
export interface PriceConstraint { 'category' : string, 'minPrice' : string }
export interface Product {
  'id' : string,
  'categoryId' : string,
  'name' : string,
  'description' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StoreSettings {
  'currency' : Currency,
  'storeName' : string,
  'contactEmail' : string,
  'storeDescription' : string,
  'taxRate' : number,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'addCategory' : ActorMethod<[CategoryV2], boolean>,
  'addProduct' : ActorMethod<[string, bigint, ExternalBlob, string], undefined>,
  'addToBasket' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearBasket' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  /**
   * / Only called on init
   */
  'createDefaultCategoriesAndPriceConstraints' : ActorMethod<[], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'editCategory' : ActorMethod<[string, Category], undefined>,
  'finishBatchUpload' : ActorMethod<[], undefined>,
  'getAdmins' : ActorMethod<[], Array<Principal>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBasket' : ActorMethod<[], Array<BasketItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<CategoryV2>>,
  'getCategory' : ActorMethod<[string], [] | [CategoryV2]>,
  'getPriceConstraint' : ActorMethod<[string], [] | [PriceConstraint]>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getStoreSettings' : ActorMethod<[], [] | [StoreSettings]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeAdmin' : ActorMethod<[Principal], undefined>,
  'removeFromBasket' : ActorMethod<[string], undefined>,
  'reorderCategories' : ActorMethod<[Array<CategoryV2>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'startBatchUpload' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCategory' : ActorMethod<[Category], undefined>,
  'updateStoreSettings' : ActorMethod<[StoreSettings], undefined>,
  'uploadProductImage' : ActorMethod<
    [string, ExternalBlob, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];